### PR TITLE
Small typos in two propositional-logic/syntax-and-semantics

### PR DESCRIPTION
**Pull request by feffemannen**
A few typos corrected. This is my first ever pull request so I'm crossing my fingers..

### CODE REVIEW

**Comment by rzach** [comment]
Hi! Thanks for these. Any particular reason you think \pValue should not just take two arguments? I think I'd prefer it if it was done the same as \Value, ie, \pValue{v}{!A}. (Come to think of it maybe we should take the opportunity to switch the order of arguments; it's confusing to have \Value{t}{M} but \pValue{v}{A}.

**Comment by feffemannen** [comment]
Ah, yes. That was the only way I could correct the typo in

```
Given a !!{valuation}~$\pAssign{v}$, define the evaluation function
$\pValue{v} \colon \Frm[L_0] \to \{\True, \False \}$ inductively by:
```
without hardcoding the \overline into the code. Maybe there's an easier way.

**Comment by rzach** [comment]
Good point.

**Comment by feffemannen** [comment]
Missed that. Will this do?

**Comment by feffemannen** [comment]
Wow. Now I got lost in the git jungle trying to change a already submit commit. Not sure what's happened now to be completely frank.

**Comment by rzach** [comment]
Trial by fire. But you did everything right.

**Pull request merged**
