### PR TITLE
Remove irrelevant objects from Theorem 7.6 

### PR DESCRIPTION
**Pull request by marcelolynch**
Fixes a small typo in a footnote defining "vector" notation for parameters in a formula

### CODE REVIEW

**Comment by marcelolynch** [comment]
Not sure if this merits a PR or if raising an issue is more appropriate.

**Comment by marcelolynch** [comment]
I also notice that this definition is sort of irrelevant? The formula $\phi$ and sets $\overline{c}$ are not used in the Theorem, and indeed there is an additional explanation for "parameters" a little bit later which doesn't use the notation.

**Comment by timbutton** [comment]
I endorse the change - looking at the version I have on my machine, I didn't use vector notation there, and didn't have the footnote; I guess someone else added it? Or maybe I lost track of things.

**Comment by rzach** [comment]
Great thanks to both of you!

**Comment by marcelolynch** [comment]
It seems that the line was supposed to be commented (if you check line 17 before my last commit, it ends with `% for`). I tracked other uses of the "vector notation" and it is safe to delete it here (the notation is defined again and used in section 12.5).

**Pull request merged**
