### PR TITLE
Minor typos in soundness proof

### PR DESCRIPTION
**Pull request by lockhartthomas**
Three minor typos in proof of soundness. Corrected.

### CODE REVIEW

**Comment by rzach** [comment]
I've fixed the "and" but the other line is as it should be!

**Comment by rzach** [comment]
But keep them coming.  That proof has to be made better.

**Comment by lockhartthomas** [comment]
No, it isn't. If M satisfies phi->psi, then either M fails to satisfy phi or M satisfies psi. If M fails to satisfy phi->psi, then it automatically satisfies Gamma=>Delta.

**Comment by rzach** [comment]
Oh right, sorry, I was looking at the wrong file!

**Comment by lockhartthomas** [comment]
Will do!

**Pull request merged**
