### PR TITLE
Missing condition in statement of unique readability

### PR DESCRIPTION
**Pull request by lockhartthomas**
Statement of unique readability for atomic formulas missing a
condition. I fixed it.

### CODE REVIEW

**Comment by rzach** [comment]
Thanks! I can cherry-pick that one commit that has the change in it.

**Comment by lockhartthomas** [comment]
Thanks. Sorry for the mess; my first try!

**Comment by rzach** [comment]
Couldn't do this cleanly after all because the branch was deleted?  Anyway, change made, thanks again!

**Comment by lockhartthomas** [comment]
Yes, I could't figure out how to stop the problem affecting all my other
branches, so I ended up deleting the whole branch. Likely a newbie mistake.
In any case, I now see how to do it neatly. More to follow.

**Pull request closed without merging**
